# Generated by Django 3.1.6 on 2021-02-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='is_main',
        ),
        migrations.AddField(
            model_name='listing',
            name='cover',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
