# Generated by Django 3.1.6 on 2021-02-20 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20210220_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='state2',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='listings.state'),
            preserve_default=False,
        ),
    ]
