# Generated by Django 3.1.6 on 2021-02-20 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_state2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['state2']},
        ),
        migrations.RemoveField(
            model_name='listing',
            name='state',
        ),
        migrations.AlterField(
            model_name='listing',
            name='state2',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='listings.state'),
        ),
    ]
