# Generated by Django 3.1.7 on 2021-03-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('fa_icon_class', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='UserField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('linkedin', 'Linkedin'), ('instagram', 'Instagram'), ('pinterest', 'Pinterest')], max_length=50)),
                ('value', models.CharField(max_length=250)),
            ],
        ),
    ]
