# Generated by Django 3.1.6 on 2021-02-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfield',
            name='name',
            field=models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('linkedin', 'Linkedin'), ('instagram', 'Instagram'), ('pinterest', 'Pinterest')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userfield',
            name='value',
            field=models.CharField(max_length=250),
        ),
    ]
