# Generated by Django 3.1.6 on 2021-02-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realtor',
            options={'ordering': ['-hire_date']},
        ),
    ]
